ae-utbm/sith

.github/workflows/deploy.yml
.github/workflows/unittests.yml

They are only trigerred on PRs

Unit tests do not run on master push

---

.github/workflows/deploy.yml
.github/workflows/unittests.yml
subscription/models.py

Going back to actions again

---

subscription/views.py

There is still some code that is deprecated and needs to be removed or replaced.

Edited deprecated code

---

core/templates/core/500.jinja
sith/settings.py
sith/urls.py

Specified default environment for issues

Updated sentry modal SDK

---

core/models.py
core/templates/core/user_detail.jinja
sith/settings.py

This ensures everyone can understand the code
Completes #460

hot fix: Updated variable names & comments

---

com/models.py

SInce it was asked by the AE staff. We would like to change the current banner.

:lipstick: Modification of banner

---

.mailmap

Added back the **git** .mailmap file

---

com/models.py

I hope it will be the last time we have to do that change

Return to classical weekmail banner

---

core/static/core/style.scss
core/templates/core/base.jinja

Straightforward pull request and commit to remove Pinktober from AE website:
After:

Removing pinktober for AE

---

club/tests.py
sith/settings.py

Edited bar manager club to pdf (pdfesti)

---

poetry.lock
pyproject.toml

Revert "Dépendances poetry & Nettoyage de la doc"

---

counter/static/counter/js/counter_click.js

Ca résoud le problème de l'autocomplétion cassée sur les comptoirs.

Repair NaN bug for autocomplete on counter click

---

core/static/core/header.scss
core/static/user/user_tools.scss
core/templates/core/base.jinja
core/templates/core/user_clubs.jinja
core/templates/core/user_tools.jinja

Fix divers pour la PR avant mise en prod
- #578
- Réajout du nom d'utilisateur dans la barre de navigation
- Clarification des boutons dans le popup des notifs
- Fix de la scrollbar qui apparaissait tout le temps dans le popup des notifs
- Fix de l'affichage des lieux de vies dans l'onglet comptoir de la page des outils
- Fix de l'affichage des comptes en banque dans l'onglet de comptabilité de la page des outils
- Fix du tableau des clubs dans la page des clubs de l'utilisateur
- Mise en cache de la version du site en bas de page

[CSS] Suite à la PR #578

---

core/models.py
core/static/core/header.scss
core/static/sas/picture.scss
core/static/user/user_detail.scss
core/static/user/user_edit.scss
core/templates/core/base.jinja
core/templates/core/user_detail.jinja
core/templates/core/user_edit.jinja
core/utils.py
locale/fr/LC_MESSAGES/django.po
sas/templates/sas/picture.jinja

- Fix des images qui déborde dans la page d'édition d'utilisateur
- Fix erreur 500 lorsqu'on voulait modifier son profil
- Fix photo de profil mal proportionnée dans la barre de navigation
- Fix photo de profil mal proportionnée dans les tags sous une photo
- Lorsqu'un logo de promo n'est pas trouvé sur la page de l'utilisateur, un placeholder apparaît à la place

[HOTFIX] Fixes pour les bugs relevés en prod

---

core/static/sas/album.scss
core/static/sas/picture.scss
sas/models.py
sas/templates/sas/album.jinja
sas/templates/sas/picture.jinja

- Modification du CSS pour les photos verticales et ajout d'une couleur de fond unifiée à travers le SAS
- Fix des problèmes de cache lié aux permissions d'affichages des photos à modérer dans le SAS

[FIX] Fixe les problèmes lié au cache dans le SAS

---

core/static/core/header.scss
core/static/core/navbar.scss
core/static/sas/album.scss
core/static/sas/picture.scss
core/templates/core/base.jinja
sas/models.py
sas/templates/sas/album.jinja
sas/templates/sas/picture.jinja

- Le texte `Rechercher` dans la barre de recherche est maintenant plus clair
- Le texte survolé dans le header est désormais gris au lieu de bleu clair
- La navbar se transforme en menu hamburger sur petit écran (mobiles)
- L'image de profil était mal proportionnée dans le header sur mobile
- Le nom d'utilisateur était décalé vers la droite dans le header (sur mobile)

[FIX] Fixes & Améliorations du nouveau CSS

---

club/templates/club/club_sellings.jinja
club/templates/club/club_tools.jinja
com/templates/com/news_detail.jinja
core/templates/core/base.jinja
core/templates/core/register.jinja
core/templates/core/user_account.jinja
core/templates/core/user_account_detail.jinja
counter/templates/counter/cash_summary_list.jinja
counter/templates/counter/counter_list.jinja
counter/templates/counter/counter_main.jinja
counter/templates/counter/last_ops.jinja
counter/templates/counter/refilling_list.jinja
locale/fr/LC_MESSAGES/django.po
pedagogy/templates/pedagogy/uv_detail.jinja
pedagogy/templates/pedagogy/uv_edit.jinja

- Some links were not up to date anymore and have been removed for clarity
- Fix some typos in translations strings

Links update & translations typos fixes

---

eboutic/templates/eboutic/eboutic_main.jinja
locale/fr/LC_MESSAGES/django.po

Retire le panel de l'offre des eurockéennes.
Pour faire ça proprement, j'ai merge master dans taiste, puis j'ai rajouté un commit pour retirer le panel. Par contre, si le partenariat se pérennise, faudra mettre un mécanisme permettant au bureau d'activer le partenariat, ça sera plus propre que de faire tous les ans un commit pour l'ajouter, puis un commit pour le retirer.
Après cette PR, je pense que taiste sera prête pour être merge avec master.

Remove eurocks

---

core/middleware.py
core/templates/core/login.jinja
core/templates/core/password_reset.jinja
core/templates/core/register.jinja
core/templates/core/register_confirm_mail.jinja
core/templatetags/extensions.py
core/tests.py
core/urls.py
core/views/forms.py
core/views/user.py
locale/fr/LC_MESSAGES/django.po
poetry.lock
pyproject.toml
sith/honeypot.py
sith/settings.py

Ajoute un field honeypot pour filtrer les bots
* Couche de compatiblité avec jinja via une extension qui fait wrapper
* Ajout sur les pages importantes
* Login
* Password reset
* Register

Implement mechanisms to block bots on authentication views

---

forum/models.py
forum/tests.py

On a une erreur 500 quand on écrit dans un topic à la suite de la dernière mise à jour Django.

Fix forum topic creation error

---

core/templates/core/base.jinja
counter/models.py
counter/signals.py
counter/templates/counter/activity.jinja
counter/templates/counter/counter_click.jinja
counter/urls.py
counter/views.py

Quelques refactors qui permettent d'optimiser certaines requêtes db, de mieux utiliser la cached_property `Counter.barmen_list` et d'alléger un peu les vues pour la connexion et la déconnexion des barmen

Refactor on counters

---

core/static/sas/picture.scss
core/static/user/user_godfathers.scss
sas/api.py
sas/schemas.py
sas/templates/sas/picture.jinja
sas/tests/test_api.py
sas/views.py

Yom a fait remonter que le bouton pour se détag d'une photo est cassé.
J'ai réparé en profitant au passage pour RESTifier le truc.

Fix button to remove a user from picture

---

core/management/commands/check_fs.py
core/management/commands/compilestatic.py
core/management/commands/markdown.py
core/management/commands/repair_fs.py
core/management/commands/setup.py
core/models.py
core/scss/finder.py
core/scss/processor.py
core/templatetags/renderer.py
core/tests.py
core/utils.py
core/views/files.py
sas/models.py
sith/settings.py

Amélioration de la commande compilestatic :
- Ca ne casse plus quand des fichiers en importent d'autres
- Le CSS généré est minifié, ce qui devrait significativement diminuer la taille de nos fichiers statics.

Better scss

---

pedagogy/schemas.py
pedagogy/tests/test_api.py

Quand on est passé à Ninja pour l'api, on a perdu la recherche full search du guide des uvs.
Je la réintroduit ici.

Use full text search in pedagogy uv search api

---

core/templates/core/user_pictures.jinja
sas/api.py
sas/schemas.py

Ajout des dossiers avec les noms des albums dans le zip généré pour les photos

Add albums in zip file

---

club/admin.py
com/admin.py
core/admin.py
counter/admin.py
eboutic/admin.py
election/admin.py
forum/admin.py
launderette/admin.py
pedagogy/admin.py
sas/admin.py
subscription/admin.py

use autocomplete_fields in admin

---

core/apps.py
core/management/commands/install_xapian.py
core/management/commands/markdown.py
core/models.py
core/views/user.py
forum/views.py
pedagogy/migrations/0002_auto_20190827_2251.py
pyproject.toml
rootplace/management/commands/delete_all_forum_user_messages.py
rootplace/views.py
sith/settings.py

Comme ça on n'oubliera plus de retirer les print avant d'ouvrir une PR.

T2 ruff rule

---

core/admin.py
counter/apps.py

Une upgrade de django a pété les operation logs, c'est fixé ici

Fix operation logs

---

core/static/core/js/script.js
sas/templates/sas/album.jinja

Back et previous du navigateur ne fonctionnent pas très bien avec la nouvelle pagination ajax actuellement

Fix back function in album pagination

---

core/static/core/js/script.js
core/templates/core/macros.jinja
pedagogy/templates/pedagogy/guide.jinja
sas/templates/sas/album.jinja

Fix le retour arrière dans la pagination du guide des uvs.
Création d'un composant réutilisable pour la pagination alpine via une macro

Ajax navigation history in uv guide

---

core/templates/core/user_pictures.jinja

Better browser compatibility for user picture page

---

core/templates/core/user_edit.jinja
core/views/forms.py
locale/fr/LC_MESSAGES/django.po

J'ai remarqué que le champ d'image des users accepte n'importe quoi comme type.
C'est vraiment pas ouf, surtout qu'on peut vraiment uploader n'importe quoi et c'est ouver dans PIL.
Il y a un monde où c'est un vecteur d'attaque alors vaut mieux prévenir que guerrir

Better form for user submiting images

---

core/templates/core/macros.jinja

fix promo img on clicks

---

core/management/commands/populate.py
core/templates/core/user_edit.jinja
core/urls.py
core/utils.py
core/views/files.py
core/views/forms.py
core/views/user.py
sas/models.py

Conversion systématique des images en webp, pour une meilleure compression.

Better images format

---

core/models.py
core/views/files.py
core/views/user.py
sas/tests/test_views.py
sas/views.py

fix undeletable SAS pictures

---

core/api.py
core/schemas.py
core/tests/test_user.py
core/views/site.py

Les utilisateurs n'étaient plus triés par ordre d'activité dans la recherche.

User ordering

---

counter/views.py

841 sales selection performance

---

club/models.py
club/tests.py
com/views.py
core/management/commands/populate.py
core/management/commands/populate_more.py
core/utils.py
galaxy/models.py
rootplace/views.py
subscription/models.py

Les tests qui foirent entre minuit et 2h, c'est un peu chiant.
Et en plus, ça veut dire que si les tests foirent, c'est un vrai bug qu'il y a en-dessous.

Fix localdate

---

docs/howto/translation.md
docs/tutorial/install.md

Réorganisation des instructions d'installation pour éviter que les gens se tapent une erreur quand ils tentent de lancer la commande `setup`.
J'ai aussi rajouté une ligne pour rappeler aux gens de faire un `apt update`. Parce que je jure que pour l'instant, tous ceux que j'ai vu installer le projet arrivaient pas à le faire à cause de ça.

Better install doc

---

core/models.py
core/tests/test_files.py

rollback des checks d'ownership sur SithFile, mise en place de tests pour vérif ça

Fix sas owner

---

docs/reference/stock/models.md
docs/reference/stock/views.md

J'ai juste viré le reste de docs qui restaient des stocks et qui empêchaient la doc de se générer correctement, testé en local ça génère bien comme il faut maintenant

delete stocks remaining docs

---

core/tests/test_user.py
eboutic/models.py

Dans la PR #859 j'avais optimisé le chargement des pages des comptes utilisateurs en créant des méthodes de QuerySet qui réalisaient des aggrégations sur la somme totale associée à des achats, des rechargements ou des factures eboutic.
Dans le lot, la requête pour récupérer le montant total des rechargements eboutic n'était pas bonne. Elle utilisait une `Subquery` qui ne faisait pas bien l'aggrégation. Pour les factures eboutic qui ne comportent qu'un seul item, le problème n'est pas visible. En revanche, quand il y a plusieurs items, la requête retourne des résultats incohérents avec SQLite, et plante carrément avec Postgres.
Heureusement, ce que je voulais réaliser est bien documenté par Django, donc un coup de RTFM m'a permis de réparer ça.

fix: InvoiceQuerySet.annotate_total()

---

core/tests/test_user.py
core/views/user.py
eboutic/models.py

Bon bah, mauvaise jointure dans le dernier fix. Ca plantait toujours.

fix: InvoiceQuerySet.annotate_total() (but this time good)

---

pyproject.toml

on va éviter de se retrouver avec des breakpoint en prod en vrai

fix ruff breakpoint

---

poetry.lock
pyproject.toml

On va faire plaisir à dependabot

Upgrade python dependencies

---

core/static/webpack/utils/select2.ts

La construction des résultats select2 était construite de manière naïve par interpolation, introduisant une faille XSS incroyablement dangereuse et facile à exploiter. C'est ma faute.

Fix xss on select2 results

---

.github/actions/setup_project/action.yml
.github/workflows/deploy.yml
.github/workflows/taiste.yml

Amélioration de la CI.
Si possible, on va essayer de la rendre plus rapide.
> Disclaimer : je vais faire beaucoup de petits commits de merde, pour bien tester la config. Je ferai un squash à la toute fin.

Refactor CI

---

.github/actions/setup_project/action.yml
eboutic/static/webpack/eboutic/eboutic-index.ts
eboutic/templates/eboutic/eboutic_main.jinja

Introduit TS pour l'eboutic.
En raison de la manière dont l'eboutic marche, ça représente très peu de modifications. Une interface, un peu de typage et c'est plié.

Migrate eboutic to Typescript

---

core/static/core/components/nfc-input.scss
core/static/webpack/core/components/nfc-input-index.ts
core/static/webpack/types/web-nfc.d.ts
core/templates/core/widgets/nfc.jinja
core/views/forms.py
locale/fr/LC_MESSAGES/django.po
locale/fr/LC_MESSAGES/djangojs.po

Transforme le widget nfc en un web component et ajoute une jolie animation de scan quand on l'utilise

Improve nfc widget

---

.github/workflows/deploy.yml

Faut ajuster les credentials dans github avant de valider ça et j'ai pas les droits.
C'est à toi de le faire @imperosol

Enable sentry workflow again

---

core/auth_backends.py
core/management/commands/populate.py
sith/settings.py

Pour gérer le retour sur le système de perm django sans pour autant mettre notre code à la poubelle, on peut écrire un backend d'authentification qui modifie juste ce qu'il faut du backend par défaut de django.

Custom auth backend

---

core/auth_backends.py

Dans la PR introduisant un backend d'auth custom, j'avais rajouté un ajout dynamique du groupe `Subscriber` dans le cas où l'utilisateur est cotisant. Sauf que j'avais mal fait le queryset. donc ça marchait pô.

Fix custom auth backend

---

core/static/core/forms.scss
core/static/core/header.scss
core/static/core/style.scss
core/static/user/user_edit.scss
core/templates/core/user_edit.jinja
core/views/forms.py
counter/forms.py
counter/templates/counter/product_list.jinja
eboutic/templates/eboutic/eboutic_makecommand.jinja

Amélioration du style des formulaires. Pour faire ça, je me suis très fortement inspiré de [ceci](https://nielsvoogt.github.io/nice-forms.css), que j'ai essayé d'adapter aux besoins du site.
Quelques aperçus :

rework form style

---

docs/howto/translation.md
locale/fr/LC_MESSAGES/django.po
locale/fr/LC_MESSAGES/djangojs.po

JPP de perdre des heures à résoudre des conflits sur les lignes des trads quand je rebase

Remove line numbers from locale files

---

com/static/com/css/news-detail.scss
core/static/core/forms.scss
counter/forms.py
locale/fr/LC_MESSAGES/django.po

le `display:block` avait disparu des helptext, ce qui rendait leur affichage bizarre. Et il manquait quelques détails sur le `ProductForm`

small form fixes

---

com/static/bundled/com/components/ics-calendar-index.ts
com/templates/com/news_list.jinja
core/static/core/colors.scss
core/static/core/style.scss
core/templates/core/base.jinja
locale/fr/LC_MESSAGES/django.po

* Improve code readability of calendar details
* Add link to AE Dev discord in useful links
* Add link to github at the bottom

Improve welcome page

---

counter/static/bundled/counter/components/counter-product-select-index.ts

Petit bout de code pour que la recherche par code ai une plus grosse priorité

Make code matching rank first in counter click

---

election/static/election/css/election.scss
election/templates/election/election_detail.jinja

Testé sur safari et firefox
Règle les problèmes d'overflow du tableau et les liens de conexion et déconexion qui ont un style inatendu.
Élection publique non connecté
Élection publique connecté admin
Élections publique connecté participant

Quick fix for election display

---

core/static/core/components/ajax-select.scss
core/static/core/forms.scss

make ajax select appearance consistant with other inputs

---

core/management/commands/populate.py
counter/tests/test_counter.py
counter/views/click.py

* Add tests
* Add tests for cons/dcons

Fix selling ordering bug that created "not enough money" errors

---

com/static/com/components/ics-calendar.scss

Fix wrong overflow on chrome for calendar

---

counter/models.py

Renommage de l'attribut `check` en `is_check` dans la methode `__getattribute__()` de `CashRegisterSummary`

is_check attribute refactor

---

core/static/core/style.scss
counter/schemas.py
counter/static/bundled/counter/product-list-index.ts
counter/templates/counter/product_list.jinja

Ajoute la possiblité de filtrer les produits par comptoir et par club sur la page des produits.

add club and counter filters on product list page

---

core/static/bundled/utils/api.ts
counter/static/bundled/counter/product-list-index.ts
sas/api.py
sas/schemas.py
sas/static/bundled/sas/album-index.ts
sas/static/bundled/sas/components/ajax-select-index.ts
sas/static/bundled/sas/user/pictures-index.ts
sas/templates/sas/album.jinja
sas/tests/test_api.py
sas/views.py
sas/widgets/ajax_select.py
tsconfig.json

On utilise Alpine et notre API pour afficher les albums dans le SAS plutôt que de le faire uniquement backend. Je n'ai pas mis de pagination, parce que jusqu'ici il n'y en avait pas. Si on en ressent le besoin, on pourra en mettre une autre plus tard.
Cette PR prépare #1015

ajaxify album loading

---

locale/fr/LC_MESSAGES/django.po
locale/fr/LC_MESSAGES/djangojs.po
rootplace/forms.py
rootplace/tests/test_merge_users.py

ajout de la méthode clean dans MergeForm pour invalider la tentative de fusion de deux utilisateurs identiques

Check that a user cannot be merged into itself

---

com/api.py
com/ics_calendar.py
com/static/bundled/com/components/ics-calendar-index.ts
com/tests/test_api.py

Bye bye, le calendrier google. Tu nous manqueras pas beaucoup.

Remove external calendar

---

eboutic/templates/eboutic/eboutic_main.jinja
locale/fr/LC_MESSAGES/django.po

Partenariat avec les Eurockéennes 2025 sur l'eboutic

Eurockéennes 2025

---

core/static/core/style.scss
counter/forms.py
counter/tests/test_customer.py
eboutic/api.py
eboutic/models.py
eboutic/static/bundled/eboutic/makecommand-index.ts
eboutic/templates/eboutic/eboutic_billing_info.jinja
eboutic/templates/eboutic/eboutic_main.jinja
eboutic/templates/eboutic/eboutic_makecommand.jinja
eboutic/tests/test_billing_info.py
eboutic/urls.py
eboutic/views.py
locale/fr/LC_MESSAGES/django.po
locale/fr/LC_MESSAGES/djangojs.po

En tant que CEO de HTMX, je fait en sorte que les formulaires soient en pur html

Use htmx to fill up billing info

---

core/auth/mixins.py
eboutic/templates/eboutic/eboutic_main.jinja
eboutic/templates/eboutic/eurok_fragment.jinja
eboutic/urls.py
eboutic/views.py
locale/fr/LC_MESSAGES/django.po

Ça m'a énervé les cookies de shitevent alors j'ai bricolé un formulaire de consentement
Dégagez avec votre tracking de con

Add consent form for eurok partnership

---

counter/views/cash.py
counter/views/mixins.py

Avant, on avait une caisse que les barmen relevaient à chaque perm.
Maintenant, on a un coffre, sous le bar, dans lequel les barmen mettent l'argent liquide et les tickets de caisse. Ce coffre est accessible uniquement aux trésos, donc c'est uniquement à eux que le formulaire de relevé de caisse doit être accessible, désormais.

hide cash register views to barmen

---

core/static/bundled/core/accordion-index.ts
core/static/core/accordion.scss
core/templates/core/base.jinja
core/templates/core/user_account.jinja
core/templates/core/user_detail.jinja
counter/static/bundled/counter/counter-click-index.ts
counter/templates/counter/counter_click.jinja
pedagogy/static/pedagogy/css/pedagogy.scss
pedagogy/templates/pedagogy/uv_detail.jinja

On retire ici tout appel aux accorions jquery-ui
J'ai recopié le style qu'ils avaient.
Maintenant ils sont navigable au clavier contrairement à avant.
Différence majeurs:
* on peut fermer tous les accordions (c'est pas très important)

Remove jquery-ui accordions

---

core/static/core/accordion.scss

Fix bad css scoping on accordions

---

club/forms.py

La requête pour sélectionner les comptoirs à afficher sur la page des ventes d'un club marche très mal sur la db de prod (on parle de 37sec la requête).
Avec cette nouvelle requête, ça devrait mieux marcher (j'ai vérifié avec un explain analyze sur la vraie db, cette fois)

Fix counter selection performance on SellingForm

---

core/static/bundled/core/navbar-index.ts
core/templates/core/base.jinja

Bon ben à vouloir éviter un bug nul sur la navbar, j'en ai crée un plus gros D:

Fix click on navbar

---

package-lock.json
package.json
sas/static/bundled/sas/user/pictures-index.ts
sas/templates/sas/macros.jinja
sas/templates/sas/user_pictures.jinja
tsconfig.json

Les photos utilisateur étaient dans le mauvais ordre, parce que JS fait des choses bizarres avec l'ordre de ses records.
Et la page scrollait pas vers l'album voulu. Il faut rajouter un `$nextTick`

fix: user pictures ordering

---

core/static/core/footer.scss
core/static/core/style.scss
core/templates/core/base.jinja
core/templates/core/base/footer.jinja

Après :
Avant :
Aucun changement visuel sur desktop/tablet

Màj du footer sur mobile

---

club/migrations/0013_alter_club_board_group_alter_club_members_group_and_more.py
club/models.py
com/migrations/0008_alter_news_options_alter_newsdate_options_and_more.py
com/models.py
core/migrations/0043_bangroup_alter_group_description_alter_user_groups_and_more.py
core/models.py
counter/migrations/0030_returnableproduct_returnableproductbalance_and_more.py
counter/models.py

cf. https://docs.djangoproject.com/en/5.1/releases/5.1/#id2

replace deprecated CheckConstraint.check by CheckConstraint.condition

---

com/templates/com/macros.jinja
core/templates/core/base/header.jinja
core/templates/core/widgets/autocomplete_select.jinja
counter/templates/counter/counter_click.jinja

- Retire les espaces dans les autocomplete, ce qui permet d'économiser quelques ko de bande-passante
- Retire quelques requêtes db au chargement de la page d'accueil.

Optimisations
