ae-utbm/sith

.github/workflows/deploy.yml
.github/workflows/unittests.yml

Each time a commit is merged into master, this create a new release on Sentry (using [Sentry Release Action](https://github.com/marketplace/actions/sentry-release))
Also, `deployment` action is now only triggered on push to master, whereas before this action was triggered right after the `unit testing` action. This led to issues where deployment was triggered after unit testing for pull requests.

Sentry Release Integration & Workflow updates

---

.github/workflows/deploy.yml

Sentry new release only triggers when deployment is successful

Editing workflow process

---

core/models.py
core/templates/core/user_detail.jinja
sith/settings.py

Needed for the case of the integration week, by editing `settings.py` or `settings_custom.py` and adding the club `id` to the list.

Selected club members can now see subscriptions

---

core/templates/core/base.jinja

Easy as that aha
> I've taken the time to delete the associated forum page on the production site

Switched Calendar link to Elections list link (as it was unused)

---

eboutic/templates/eboutic/eboutic_main.jinja

Résoud deux bugs :
- les alt des images des produits n'étaient pas bonnes
- les noms de produits avec une apostrophe dedans n'étaient pas cliquables

bux fixing on new eboutic

---

eboutic/templates/eboutic/eboutic_makecommand.jinja
eboutic/urls.py

J'ai trouvé l'erreur. En fait c'était tout con. Il y avait un slash en trop à la fin de l'url pour la réponse de la banque. Les paiements étaient valides, en fait. Juste on recevait pas la réponse.

Correct wrong et_autoanswer url

---

.github/workflows/taiste.yml

Petite modification du yml pour les actions github pendant le déploiement sur le site de test.
Ca remplace juste le `git pull` par un `git fetch`, puis `git reset --hard origin/taiste` pour s'assurer qu'il n'y ait pas de conflit au cas où on merge une branche sur taiste après qu'il y ait eu push force depuis master avant ça.

Ci cl edit

---

counter/models.py

En cherchant pourquoi la banque pouvait bloquer la requête, je me suis rendu compte que c'est le code alphabétique et pas le code numérique qui était mis dans la requête.
Comme la librairie django_countries est bien foutue, ça a été simple à corriger.
J'espère que c'est la dernière modification avant que la banque accepte les requêtes 3DSecure v2 du site.

Eboutic 3DSv2 patch

---

.github/workflows/deploy.yml
.github/workflows/taiste.yml

Résoud le soucis lié à dependabot.
Le problème venait du fait que l'on faisait un `poetry update` et non un `poetry Install`.  Un update écrit dans `poetry.lock`, alors qu'un Install lit ce fichier. C'est là toute la différence. 
Cette PR change donc les workflows.
Laisser ce bot apporte beaucoup de sécurité, vu qu'il nous prévient des changement, et aussi des vulnérabilités au niveau des dépendances.

Changement du comportement de Poetry dans les workflows

---

eboutic/forms.py
eboutic/static/eboutic/css/eboutic.css
eboutic/static/eboutic/js/eboutic.js
eboutic/templates/eboutic/eboutic_main.jinja

https://github.com/ae-utbm/sith3/blob/35261564269cc0272cfaf40d890e4383d1ab0c0d/eboutic/forms.py#L104
J'ai fait en sorte de remplacer les `\"` par des `'`, c'est le moyen le plus simple pour que le regex puisse valider la string, sinon faudrait réadapter le regex pour ça, mais j'ai pas la tête à faire du regex vu la tête du truc mdr.
J'ai modifié l'apparence des items pour qu'ils soient tous de la même largeur, quand on clique une fois sur un item ça fait une légère animation sur la couleur de fond & ça met l'emoji 🛒 en haut à droite de l'item, j'ai aussi fait en sorte que si le nom de l'article est trop grand ça le coupe proprement & que l'item s'allonge en hauteur (plutôt qu'en largeur actuellement), 
<p align="center">
</p>
J'ai un poil adapté le panier pour que les boutons `+` & `-` …

[Eboutic] Fix double quote issue & improved user experience on small screen

---

club/admin.py
com/admin.py
core/admin.py
core/lookups.py
counter/admin.py
counter/models.py
eboutic/admin.py
election/admin.py
launderette/admin.py
pedagogy/admin.py
pedagogy/models.py
subscription/admin.py

Amélioration des pages admins du site.
D'une part, ça rend le site admin un peu plus facile à parcourir.
D'autre part, ça évite d'avoir un timeout à chaque fois qu'on tente d'accéder à la page d'un modèle qui a une clef étrangère vers un utilisateur, un panier ou un client.

enhance admin pages

---

eboutic/templates/eboutic/eboutic_makecommand.jinja

Quand je tente de retirer manuellement le token csrf (qui n'a rien à faire là puisque la requête va vers un serveur externe, elle ne retourne pas chez nous), j'obtiens cette erreur :
Indubitablement, ça ne marche pas, mais j'appelle quand même ça un progrès.

remove csrf_token

---

counter/models.py
eboutic/models.py
eboutic/templates/eboutic/eboutic_makecommand.jinja

Cela devrait corriger le soucis suivant :
Il provenait du CSRF token qui était mal positionné, ainsi qu'un caractère spécial mal échappé.

Fix 3DSv2 implementation

---

accounting/urls.py
club/urls.py
com/urls.py
core/converters.py
core/tests.py
core/urls.py
core/views/user.py
counter/urls.py
election/urls.py
forum/urls.py
launderette/urls.py
matmat/urls.py
pedagogy/tests.py
pedagogy/urls.py
rootplace/urls.py
sas/urls.py
stock/urls.py
subscription/urls.py
trombi/urls.py

Changement des urls pour utiliser `path` au lieu de `re_path`. [Voir la doc](https://docs.djangoproject.com/en/3.2/topics/http/urls/)
`path` a l'avantage de permettre des urls plus lisibles.
Pour les cas particuliers, des convertisseurs remplacent les regex dans l'url.
D'un point de vue purement fonctionnel, ça devrait résoudre le problème des pages qui peuvent 404 selon qu'on met un `/` à la fin de l'URL ou non (par exemple, actuellement, `https://ae.utbm.fr/counter/2` marche, mais `https://ae.utbm.fr/counter/2/` est 404)

upgrade re_path to path

---

core/templates/core/base.jinja
counter/models.py
counter/tests.py

C'est très chiant de devoir modifier manuellement son URL pour arriver sur la page du comptoir, particulièrement sur téléphone (et justement, les comptoirs sont beaucoup utilisés sur tel).
Donc ici, on fait en sorte que quand on clique sur un comptoir dans le bandeau supérieur, on redirige l'utilisateur :
- s'il est barman du comptoir en question : vers la page du comptoir (sans qu'il ait à modifier manuellement l'URL)
- sinon, vers la page d'activité du comptoir (comme avant)
Pour faire ça sans rajouter de requêtes supplémentaire, j'ai modifié le Manager par défaut du modèle `Counter` afin de lui rajouter la méthode `annotate_user_is_barman(user)`, qui permet d'annoter le queryset avec un booléen qui vaut True quand l'utilisateur fait partie des vendeurs du comptoir en question, sinon …

redirect the user directly on counter if user is barman

---

counter/models.py

Il semblerait qu'il y ait eu une confusion dans l'ordre des imports qui est complètement passée sous le radar de github pendant la CI de la PR mais qui a fait échouer la CI du taiste.

resolved importError

---

counter/models.py
rootplace/tests.py
rootplace/views.py
subscription/models.py

J'ai réécrit la vue qui permettait de fusionner deux utilisateurs et écrit les tests associés.
Ca devrait résoudre tous ces problèmes qui étaient là :
- erreur quand un des deux utilisateurs n'a pas de compte pour les achats
- les groupes n'étaient pas fusionnés
- les fillots n'étaient pas fusionnés
- un utilisateur pouvait devenir son propre parrain
- perte de tout ou partie de la cotisation de l'utilisateur supprimé si l'utilisateur conservé est cotisant
Par contre, j'ai pas pu résoudre le problème de la non-fusion des images. Les images de profil de l'utilisateur resteront donc perdues. J'ai essayé de réparer, mais le problème vient de choix de conception atroces qui touchent au coeur même du site (je tiens à le redire, le concept même des SithFile était une connerie dès le début). …

Repaired merge user feature

---

eboutic/templates/eboutic/eboutic_main.jinja
locale/fr/LC_MESSAGES/django.po

Le partenariat avec les eurockéenes de cette année requiert l'implémentation de leurs billetterie au sein de l'eboutique
<details>
<summary>Screens</summary>
</details>
> En attente de validation de la part de Thibault Chausson (respo partenariat)
> A merge dès la validation

[PARTENARIAT] Ajout vitrine d'achat billets eurockéennes 2023

---

core/static/core/style.scss
core/templates/core/user_detail.jinja
core/templatetags/renderer.py
core/utils.py
counter/models.py
counter/templates/counter/stats.jinja
counter/tests.py
counter/views.py
locale/fr/LC_MESSAGES/django.po
sith/settings.py

Jusqu'à présent, la page des stats des comptoirs était très lente à charger (de l'ordre de 5 secondes en moyenne).
Le temps de chargement était pas tant dû la à la complexité des requêtes dans la vue qu'au nombre aberrant de requêtes qui se cachaient dans le template (500 requêtes plus pour des stats complètes).
Autre problème : la page n'était pas testable en local.
Cette PR règle les deux problèmes en reformulant les requêtes pour n'en laisser que 4 et rendre ça testable en local, pour le même résultat final.
La PR change aussi le style des tableaux pour les rendre un peu plus aérés et lisibles. Ca fait que concrètement, on passe de ça : 
A ça : 
A noter que ce nouveau style de tableau est global. Sur le guide des UE, par exemple, ça donne ça 
Au cas où j'ai vérifié, mais c'est bon, ça …

removed useless queries on counter stat

---

com/templates/com/news_list.jinja
core/static/core/header.scss
core/static/core/style.scss
locale/fr/LC_MESSAGES/django.po

*Demande directe du bureau*
> C'est une simple `iframe` du calendrier google, j'ai utilisé le site Styled Calendar pour l'adapter aux couleurs du site & ils ont une version responsive qu'est pas mal (celui de base de google est vraiment moche)

[ENHANCEMENT] Ajout Google Calendar des clubs & GA

---

core/static/core/navbar.scss
core/static/sas/album.scss
core/static/user/user_detail.scss
core/static/user/user_godfathers.scss
core/templates/core/user_detail.jinja
core/templates/core/user_pictures.jinja
sas/templates/sas/album.jinja

Il s'avère que j'ai utilisé la mauvaise méthode et que les photos présentes dans la page utilisateurs sont affichées en HD :/
- Les photos de l'onglet de la page utilisateur utilise désormais leur version thumbnail au lieu de leur version HD
- Une des classes du CSS du SAS a été renommée car elle empiétait sur une class de la navbar
- Le profil utilisateur a été revu pour ajouter plus d'espacement entre le tableau des cotisations et le numéro de cotisants
- Les images de forum & blouse sont de nouveau cliquable pour les afficher en grands
- Sur mobile, lorsqu'on cliquait sur le premier élément de la navbar, ce dernier avait un overlay avec des angles arrondis
- Sur mobile, les utilisateurs avec des images de profils non carrées dépassait dans l'onglet Famille

[FIX] HD pictures used instead of thumbail in user page & others bugs

---

club/models.py
core/models.py
core/static/core/navbar.scss
core/templates/core/user_pictures.jinja
core/utils.py
core/views/files.py
core/views/page.py
core/views/site.py
core/views/user.py
counter/views.py
locale/fr/LC_MESSAGES/django.po
pedagogy/views.py
rootplace/tests.py
sas/templates/sas/picture.jinja
sith/settings.py
trombi/templates/trombi/detail.jinja
trombi/templates/trombi/user_tools.jinja
trombi/views.py

- #109
De par le fait que l'utilisateur était propriétaire de son image de profil, il pouvait accéder aux URLs suivantes : `/file/<id>/` et `/file/<id>/[delete|prop|edit]` et ce malgré l'interdiction d'accès au dossier parent `profiles`.
Une méthode `can_be_managed_by(user)` a donc été créée et régis les droits de "management" des fichiers suivants les 3 règles suivantes :   
- Si le fichier n'est ni dans `/sas` ou `/profiles` alors les droits d'accès de base s'appliquent (comme auparavant)
- Si le fichier est dans `/sas`, uniquement les admins SAS & roots peuvent y accéder (car le proprio du fichier pouvait tout de même le manager sans être admin SAS ou root)
- Si le fichier est dans `/profiles`, uniquement les utilisateurs roots & membres du bureau peuvent accéder aux urls ci-dessus.
- …

[FIX] Correction de bugs

---

core/models.py
core/tests.py

This is a temporary solution to fix the cache issue #646, If you have any better solution, feel free to submit them

[FIX] Fix cached groups

---

com/tests.py
core/models.py

Repair [this](https://sentry.ae.utbm.fr/organizations/ae-utbm/issues/158/?referrer=webhooks_plugin).
The `NewsListView` view calls `User.is_com_admin` for right checking. However, the `AnonymousUser` class did not have such a method. This PR adds it.
This also adds some tests to avoid regression.

add missing method on AnonymousUser

---

.github/workflows/ci.yml
accounting/tests.py
club/tests.py
club/views.py
com/tests.py
conftest.py
core/tests.py
counter/tests.py
doc/start/install.rst
eboutic/tests.py
election/tests.py
galaxy/tests.py
pedagogy/tests.py
poetry.lock
pyproject.toml
rootplace/tests.py
sith/settings.py
sith/testrunner.py
subscription/tests.py

Jusqu'ici, les tests du projet utilisaient le runner par défaut de Django, qui est plutôt pratique, mais qui produit des rapports pas très lisibles et qui a pas des assert très ergonomiques.
Pytest permet d'améliorer ça. L'utilisation d'`assert` permet de simplifier l'écriture des tests et d'améliorer certains tests existants qui produisaient des messages d'erreur pas très utiles quand ils rataient.
Les rapports de tests sont aussi plus jolis :
Au passage, j'ai réécrit les `self.client.login(username, password)` dans les tests par des `self.client.force_login(user)`. Ca donne le même résultat, mais ça évite de perdre du temps à chaque test à hasher les identifiants.

Use pytest for tests

---

core/management/commands/install_xapian.sh
core/markdown.py
core/static/core/markdown.scss
core/static/core/style.scss
core/templates/core/base.jinja
core/templates/core/markdown_textarea.jinja
core/tests.py
doc/SYNTAX.html
doc/SYNTAX.md
poetry.lock
pyproject.toml

Mise à jour de mistune vers sa version 3.
Ca permet en passant de retirer le `Python <3.12` dans le pyproject.toml.
J'en ai aussi profité pour refaire un peu le style du rendu markdown, notamment en ce qui concerne les bouts de code et les blocs de citation.
On passe de ça :
A ça :
Le code inline change aussi : 
la line-height des paragraphes, des ul et des ol a été légèrement augmentée.
Le code utilise la police Consolas (la police de Notepad, tmtc).
Les blocs de code et les blocs de citation sont un peu indentés, sauf sur petits écrans, où l'indentation est retirée.
Les tableaux ne prennent plus la totalité de l'espace (ce qui donnait des tableaux étrangement larges), mais seulement ce dont ils ont besoin.
J'ai rajouté du padding au-dessus des titres :
J'ai retiré la barre de …

Update mistune (0.8 => 3.0)

---

core/static/core/markdown.scss

Dans le commit 30948f1701587c1de7b766190519cc295579255a, j'ai changé le style des bouts de code. Mais il se trouve que la police utilisée n'est pas disponible sur tous les OS.
Donc je répare ça ici

Fix markdown style for code

---

core/templatetags/extensions.py
core/utils.py
forum/templates/forum/reply.jinja
forum/tests.py
forum/views.py
sith/honeypot.py
sith/settings.py

Quand on a mis le logging du honeypot, on a oublié le timestamp et on a foutu le mauvais header pour avoir l'ip du client.

better honeypot logging

---

accounting/tests.py
club/tests.py
com/tests.py
counter/tests.py
eboutic/tests.py
election/tests.py
galaxy/tests.py
pedagogy/tests/test_api.py
pedagogy/tests/tests.py
rootplace/tests.py
sas/tests/test_api.py
subscription/tests.py

Pytest n'aime pas les classes de test qui ne commencent pas par Test et ne les détecte pas sauf si ils héritent de TestCase.
Pour éviter les inconsistances et les erreurs futurs, j'harmonise tous les noms de class de test.

Harmonize test names

---

core/templates/core/user_pictures.jinja
core/views/user.py

Yom a fait remarquer que l'ordre dans lequel les photos sont affichées sur le profil utilisateur est inversée (c'est arrivé, précisément dans ce commit : 3046438cb1de9bd79bb042843391aa6c3486a5c6. C'est ma faute, déso).
La PR répare (avec au passage un tout petit refactor sur la manière de grouper les photos par album)

fix album order for user pictures

---

core/management/commands/populate_more.py
core/management/commands/setup.py
poetry.lock
pyproject.toml

Jusqu'ici, la commande populate créait des données de base pour faire tourner le site. Mais c'était un peu léger : une dizaine d'utilisateurs, 1 membre à l'AE, à peine plus au Troll, aucune permanence dans les comptoirs, une seule UV, très peu de produits.
Ca permettait de vérifier que ça marche, mais pas de faire des tests personnels un peu plus poussés. Par exemple, difficile de vérifier que la pagination marche bien quand on n'a pas assez d'items pour déjà remplir la première page. Ca faussait aussi les résultats de ce qu'on lisait sur la debug-toolbar de Django, vu qu'on voit pas la différence entre une requête lente et une requête rapide quand une db a peu d'entrées, et qu'on ne voit pas non plus les problèmes de N+1 requêtes quand N=1.
Donc j'ai rajouté une autre commande, qui ne …

Add a command to create more fixtures

---

counter/tests.py
counter/views.py

Les clicks depuis les comptoirs de club ne sont plus accessibles. Ca vient de ce qu'on tentait d'appliquer les mêmes règles de connexion que pour les comptoirs simples.

fix club counter click

---

core/lookups.py
core/models.py
core/views/files.py
counter/utils.py
counter/views.py
docs/tutorial/install-advanced.md

Les performances du SAS sont vraiment mauvaises, Même en ayant peu de photos, mon profil charge en 5 secondes. Sli, c'est plus de 20 secondes. Et pour Skia, on dépasse les 40 secondes.
Dans ce total, on a le chargement initial qui prend environ 1/4 de la durée (c'est déjà énorme, mais on s'occupera de ce problème dans une PR un peu plus tard), et la majeure partie du reste qui est occupée par l'envoi des images.
Et justement, ça pose problème, parce que notre serveur Python n'est pas vraiment fait pour servir des fichiers. Mieux vaut refiler ce travail à nginx. Pour ça, on joint à la réponse le header `X-Accel-Redirect`, et le reverse-proxy se charge du reste.
Ca suffira pas à rendre le chargement des pages du SAS instantané, mais ça devrait déjà l'accélerer (je saurais pas dire à quel …

Accel redirect

---

counter/utils.py

Quand on accède à une photo en tapant directement son url dans le navigateur, le header `HTTP_REFERER` n'est pas là, donc ça plante.

fix-referer

---

core/models.py
core/static/core/js/script.js
core/static/core/pagination.scss
core/static/core/style.scss
core/static/sas/album.scss
core/templates/core/user_pictures.jinja
core/utils.py
core/views/user.py
pedagogy/templates/pedagogy/guide.jinja
sas/api.py
sas/models.py
sas/schemas.py
sas/templates/sas/album.jinja
sas/templates/sas/macros.jinja
sas/templates/sas/main.jinja
sas/templates/sas/picture.jinja
sas/tests/test_api.py
sas/tests/test_model.py
sas/views.py

Dans cette PR :
- ajout de la méthode de queryset `viewable_by(user)`, qui filtre un QuerySet de `Picture` pour ne garder que les images visibles par l'utilisateur passé en paramètre
- Passage aux règles suivantes pour la visibilité des images :
- les root et les admins SAS peuvent tout voir
- les cotisants et anciens cotisants peuvent voir toutes les photos modérées
- les non-cotisants peuvent voir les photos sur lesquelles ils ont été identifiés
- Modification de la manière dont le cache est géré dans `Picture.can_be_viewed_by(user)`. Au lieu de chercher dans le cache si l'utilisateur est cotisant, avant de rajouter éventuellement d'autres vérifications, on regarde si la photo fait partie des photos visibles par l'utilisateur stockées dans le cache.
- Application de ces droits à la …

Sas picture selection

---

core/templates/core/search.jinja

On dévoile un peu trop de données sur les recherches d'utilisateurs pour les utilisateurs non cotisants.
On règle ça ici

User search privacy

---

.github/workflows/deploy.yml
.github/workflows/taiste.yml

Sentry est down, donc les actions de déploiement avec Sentry échouent, ce qui pourrit un peu la CI.
On remettra ça quand Sentry sera de nouveau opérationnel.

remove sentry deployment CI (until Sentry is repaired)

---

core/views/files.py

Depuis l'implémentation de l'envoi des fichiers par le reverse-proxy, le nom des fichiers n'était plus envoyé.
En fait, j'avais oublié le header "Content-disposition".

repair name of protected files

---

locale/fr/LC_MESSAGES/django.po
subscription/views.py

Les labels dans le formulaire de cotisation n'étaient pas traduits (page `/subscription`)

fix subscription form translation

---

com/models.py
core/templates/core/base.jinja
core/utils.py
locale/fr/LC_MESSAGES/django.po

L'affichage de la version n'était pas très utile, plutôt incompréhensible (un hash git tout seul, ça n'a pas spécialement de sens) et créait probablement des OSError de manière assez régulière.

remove sith version from the footer

---

club/models.py
club/tests.py

Quand on terminait une adhésion à un club, celle-ci apparaissait comme toujours en cours, jusqu'au lendemain.

fix memberships ending today

---

locale/fr/LC_MESSAGES/django.po
sas/models.py
sas/views.py

Yom a fait remonter que quand on crée un album depuis le formulaire qui est en bas des pages album, la taille maximum des noms est de 30 caractères, mais qu'on peut mettre un nom plus long si on passe par la vue d'édition des albums. En effet, dans cette vue-là, c'est la taille de `SithFile.name` qui s'applique (càd 256).
Pour résoudre ça, il faut appliquer la même limite de taille dans les deux formulaires, tout en augmentant un peu cette limite pour que ça ne soit pas punitif pour les respos SAS.

unify album name length

---

core/management/commands/install_xapian.sh

This builds Xapian with as much threads as there are CPU available, which obviously goes way faster.

Faster install xapian

---

sas/models.py

Quand une image en .jpg est uploadé, le changement d'extension en webp marche pas bien. Au lieu de se retrouver avec des .webp, on se retrouve avec des .jpgwebp.

fix image extension

---

core/management/commands/populate_more.py

La requête des sélection des clients dans la fonction de création des ventes avait une erreur qui faisait planter la commande (plus précisément, une sous-requête renvoyait plus qu'un seul élément).
Ca faisait planter sur postgres.

Repair populate more

---

core/static/user/js/family_graph.js
sas/static/sas/js/viewer.js

La suppression des images du SAS était cassée. Mais pour des raisons différentes de la dernière fois.
Deux leçons à tirer de ça :
1. Faut pas mettre de `/` à la fin des urls qui sont adressées à l'API
2. Quand npm a fini d'être installé, faut qu'on essaie de mettre en place des tests pour le front.
Les extensions des arbres généalogiques étaient cassées aussi.

Fixes after last deployment

---

core/static/core/js/script.js

La fonction `fetch_paginated` est cassée. quand on a besoin de faire des appels en plus, le `Promise.all()` retourne un tableau de tableaux. Ca fait que quand on fait `result.push(...await Promise.all(promises))`, au lieu de se retrouver avec `[a, b, c, d, e, f, g, h]`, on se retrouve avec `[a, b, c, [d, e, f], [g, h]]`.
Bref, on avait oublié le flatten.
En test, on a pas d'album avec plus de 200 photos, donc on l'avait juste pas vu.

fix: `fetch_paginated`

---

core/models.py
core/tests/test_family.py
core/tests/test_files.py

Grosse optimisation de la manière dont les droits sont appliqués. Au lieu d'explorer l'arbre des descendants noeud par noeud, on le fait étage par étage, avec une seule requête par étage.
Au total, ça demande 1 requête par étage + 3 requêtes pour appliquer les nouveaux view_groups + 3 requêtes pour appliquer les nouveaux edit_groups, ce qui fait qu'on ne dépassera pratiquement jamais la vingtaine de requêtes, là où la méthode actuelle peut nécessiter plusieurs centaines, voire milliers, de requêtes.
C'est assez critique, dans la mesure où actuellement, quand on tente d'appliquer récursivement les droits sur certains albums du sas, ça timeout.

Optimize SithFile recursive rights

---

core/search_indexes.py
core/tests/test_user.py
core/views/site.py

Après le changement de critère de tri des utilisateurs dans la recherche (`last_login` au lieu de `last_update`), la recherche des utilisateurs a cassé. J'avais oublié de rajouter le `last_login` en question dans le `UserIndex`.

Fix 500 whean searching users

---

core/static/core/style.scss

Les utilisateurs avec un aspect ratio très déséquilibré n'étaient pas bien rendus quand on les cherchait pour les identifier sur le SAS.

fix profile pictures layout in Select2 results

---

core/utils.py
sas/models.py

Yom m'a fait remonter que les photos uploadées sur le site étaient plus lourdes que les photos originales. C'est un peu gênant, surtout que l'étape d' "optimisation" prend un temps de fou (genre jusqu'à plus d'une dizaine de secondes par photo ; certains albums peuvent prendre plus d'une heure à être uploadé). Si non seulement c'est lent, mais en plus que ça gonfle la taille des images, on a le pire des deux mondes.
Donc autant retirer l'optimisation des images HD, on gagnera en temps et en mémoire, tout le monde sera content.

faster image resizing and smaller results

---

core/templates/core/user_account.jinja
core/templates/core/user_account_detail.jinja
core/tests/test_user.py
core/views/user.py
counter/models.py
eboutic/models.py

Diminue le temps de chargement des pages `/user/{user_id}/account` et `/user/{user_id}`/account/{year}/{month}` en arrangeant les problèmes de N+1 queries.
Sur les pages bien remplies, on passe d'une centaine de requêtes à juste une dizaine.

Optimize user account pages

---

core/templates/core/base.jinja
counter/api.py
counter/models.py
counter/templates/counter/activity.jinja
counter/tests/test_counter.py
counter/views.py
locale/fr/LC_MESSAGES/django.po
sith/settings.py

- Récupération de l'état des comptoirs avec juste une sous-requête
- Gestion du timeout des comptoirs en une seule requête
- Augmentation de 10 minutes du délai avant le timeout barmen
- Suppression de l'état "inactif" pour les comptoirs
- Restriction du cache uniquement à l'opération de timeout des barmen. La récupération de l'état des comptoirs n'est plus en cache.
Les effets attendus sont les suivants :
- meilleures performances du site, surtout en chargement initial
- Meilleure UX, spécialement pour les barmen, qui seront toujours redirigés vers la page du comptoir (et pas des fois sur la page d'activité, d'une manière qui leur parait complètement aléatoire)
- Réduction du besoin de devoir tout le temps recharger la page en journée. Par conséquent, les lieux de vie devraient …

Better UX and performance for counter state display

---

counter/templates/counter/product_list.jinja
counter/urls.py
counter/views.py

La requête pour obtenir la page des produits prend actuellement 900ms en moyenne. Celle des produits archivés prend 2.5s en moyenne.
Pour optimiser ça, j'ai réorganisé les vues pour obtenir tous les résultats en une seule requête, contre 2*n actuellement (où n est le nombre total de types de produits sur le site) et j'ai fait en sorte de trim le `ul`, histoire de raccourcir la réponse.

optimize: product list views

---

sith/settings.py
sith/tests.py
sith/urls.py

J'ai du rendre l'endpoint testable et fixer les settings qui me bloquaient en mode test.
On peut pas complêtement éviter de mettre l'endpoint dans les urls sinon c'est jamais rechargé dans les tests et c'est impossible à tester.

Test sentry-debug endpoint

---

counter/templates/counter/product_list.jinja
counter/views.py

La page des produits est toujours un peu lente à charger. Mais on peut encore accélérer ça en sélectionnant les valeurs à sélectionner. Ca diminue le volume retourné par la db et ça évite d'initialiser les instances de modèle. On peut gagner jusqu'à 500ms de temps de chargement avec ça.
A l'avenir, il faudra remédier à ce problème en mettant un affichage un peu plus lazy des produits. Mais pour le moment ça  permet de gagner un peu sans changer l'UX.

optimize product pages again

---

counter/management/commands/dump_warning_mail.py
counter/templates/counter/account_dump_warning_mail.jinja
locale/fr/LC_MESSAGES/django.po

Il y a encore quelques trucs qui manquent sur la commande, notamment la capacité de mettre un délai entre deux mails. Aussi, il y a des clients qui reçoivent le mail au format html sans réussir à le parser. Vu que le mail est simplissime, autant juste en faire un format texte.

Improve warning dump

---

core/templates/core/login.jinja
core/tests/test_core.py
core/views/user.py

Des utilisateurs humains se font régulièrement "éclairer" par le honeypot. Les mesures anti-bot ne devraient pas bloquer des humains.

Remove honeypot from login page

---

core/models.py
core/tests/test_user.py
subscription/views.py

La création des mots de passe utilisait le module random. Et comme dit [dans la documentation de random](https://docs.python.org/fr/3/library/random.html) :
> being completely deterministic, it is not suitable for all purposes, and is completely unsuitable for cryptographic purposes.
La création des noms d'utilisateur récupérait l'intégralité de toutes les données de toute la table `User` et instanciait toutes les instances. Avec 30k utilisateurs à récupérer, ça prenait beaucoup de temps et de mémoire. En récupérant pas débilement l'intégralité de la table, on divise par 100 le temps de l'opération.

Improve password and username generation

---

core/static/user/user_detail.scss

Since 28f397574f7b7ef54914972ed0154ce879128a3b and the removal of the `flex-basis: 50px` property from `user_profile_pictures_thumbnails`, the main picture was always displayed small-ish, at least on Firefox. Setting back a flex-basis helps getting more consistent behavior once again.
Before this fix:
After this fix:

core: fix user profile picture size

---

counter/management/commands/dump_accounts.py
sith/settings.py

- a missing `fail_silently` flag made the whole command fail if an invalid recipient is used (like closed utbm mail address)
- Not specifying the seller make the account detail pages crash.

Fix the account dump command.

---

core/schemas.py
core/static/bundled/core/components/ajax-select-base.ts

Améliore le temps de réponse des recherches Ajax :
- La route de recherche des utilisateurs avait un problème de N+1 queries ; en le réparant, on gagne entre 50ms et 100ms sur une recherche typique.
- En ajoutant un cache côté client sur les input ajax, on peut épargner beaucoup de requêtes, ce qui soulage un peu le serveur et accélère grandement le temps d'affichage des résultats. Ca devrait être particulièrement pour l'identification des utilisateurs sur le SAS (étant donné qu'en général, sur un album, l'ensemble de personnes identifiées n'est pas si grand et que le cache reste intact tout le long de la navigation au sein de l'album).

Optimize search

---

core/static/bundled/htmx-index.js
core/static/bundled/utils/web-components.ts
core/templates/core/user_preferences.jinja
core/utils.py
core/views/user.py
counter/forms.py
counter/templates/counter/add_student_card_fragment.jinja
counter/templates/counter/counter_click.jinja
counter/templates/counter/fragments/create_student_card.jinja
counter/tests/test_customer.py
counter/urls.py
counter/utils.py
counter/views/click.py
counter/views/student_card.py
locale/fr/LC_MESSAGES/django.po
sas/tests/test_api.py

CounterClick est gros, CounterClick est dangereux, CounterClick est important.
Ce serait judicieux de le splitter en plusieurs petits morceaux pour le rendre plus digeste, plus extensible, plus rapide et plus testable.
La première étape ici c'est de sortir la gestion du formulaire des cartes étudiantes et de la déléguer à une autre vue.
Dépend de https://github.com/ae-utbm/sith/pull/920

Casser counter click étape 1 : introduire des fragments

---

core/models.py
subscription/tests/test_new_susbcription.py

Depuis l'arrivée en prod de #932, la page des cotisations est accessible à n'importe qui. C'est incroyablement critique, mais on l'a hotfix, donc cette PR n'est pas non plus à déployer tout de suite.
On a vérifié toutes les cotisations créées depuis cette mise en prod, et heureusement on n'en a trouvé aucune qui semble frauduleuse.

fix access to the subscription page

---

core/templates/core/macros_pages.jinja

On avait un N+1 queries sur la page qui liste les versions d'une page, à cause d'une sélection manquée sur l'auteur de la révision.

Fix N+1 queries on page history

---

core/views/forms.py
core/views/user.py

Après la migration vers le AbstractUser, on s'est mis à afficher tous les groupes sur la page d'édition des groupes d'un utilisateur
On veut pas ça alors j'ai fixé le formulaire

Fix groups displayed on user profile group edition

---

core/static/bundled/utils/api.ts
core/static/bundled/utils/csv.ts
core/static/bundled/utils/types.d.ts
core/static/core/components/card.scss
core/static/core/forms.scss
core/static/core/style.scss
core/static/user/user_detail.scss
core/templates/core/macros.jinja
counter/static/bundled/counter/components/ajax-select-index.ts
counter/static/bundled/counter/product-list-index.ts
counter/static/bundled/counter/product-type-index.ts
counter/static/counter/css/admin.scss
counter/templates/counter/product_list.jinja
counter/urls.py
counter/views/admin.py
counter/views/mixins.py
counter/widgets/select.py
eboutic/static/eboutic/css/eboutic.css
eboutic/templates/eboutic/eboutic_main.jinja
election/static/election/css/election.scss
locale/fr/LC_MESSAGES/django.po
locale/fr/LC_MESSAGES/djangojs.po
sas/static/sas/css/album.scss
sas/static/sas/css/picture.scss

A la base, je comptais juste ajouter un bouton pour pouvoir télécharger les produits au format CSV. Mais comme c'était mieux de le faire en récupérant les données de l'API et de construire le CSV côté client, je me suis retrouvé à ajaxifier et à refaire toute la page.
- pagination de la page admin des produits
- Ajout d'un bouton pour télécharger les produits au format CSV
- Affichage des produits sous forme de cards (pour ça, j'ai extrait le style utilisé sur l'eboutic, et j'en ai fait un truc un peu plus générique).
- L'icône du produit et son prix sont visibles directement depuis la liste des produits.
- Possibilité de filter les produits par nom et par statut (archivé ou non).
- Les pages `produits` et `produits archivés` ont été fusionnées en une seule.

Rework the product admin page

---

counter/static/bundled/counter/components/counter-product-select-index.ts
counter/static/bundled/counter/counter-click-index.ts
counter/templates/counter/counter_click.jinja
locale/fr/LC_MESSAGES/django.po

On réduit le nombre de jquery sur le frontend de counter click histoire de tendre vers une page full frontend.
On remplace ici l'autocomplete jquery-ui par tom-select

Use TomSelect for product selection on counter

---

core/views/forms.py

Il y a un petit bug qui fait qu'on peut pas retirer tous ses groupes à un utilisateur

Fix error when submitting group form without any group checked

---

counter/static/bundled/counter/product-list-index.ts

L'appel à `paginated` ne fonctionnait pas pour récupérer les produits, parce que certains des paramètres passés à la fonction n'étaient pas clonables.

Fix product fetch

---

.github/actions/setup_project/action.yml
docs/tutorial/install.md

Poetry vient tout juste de passer à sa version 2.0.0.
Et on avait pas pin notre version de Poetry.
Et notre CI vient de casser.
Skill issue, un peu.
Je répare ça de façon un peu rapide et sale. On verra plus tard pour régler ce problème et faire proprement le passage à poetry 2.0 (ou à UV :sunglasses:)

Pin poetry version

---

counter/static/bundled/counter/components/counter-product-select-index.ts

La recherche par code retournait des résultats différents en prod et preprod par rapport à la version de dev.
Avant
Après

Fix inconsistent search behavior on counter click codes

---

.npmrc
core/static/bundled/core/read-more-index.ts
core/static/core/style.scss
election/static/election/css/election.scss
election/templates/election/election_detail.jinja
locale/fr/LC_MESSAGES/django.po
locale/fr/LC_MESSAGES/djangojs.po
package-lock.json
package.json
vite.config.mts

Crée un nouveau script qui gère mieux le show more / less.
Il est maintenant capable de bien découper même en présence de html.

Remove shorten dependency and use clip instead

---

club/tests.py
core/management/commands/populate_more.py
core/models.py
core/tests/test_user.py
rootplace/tests/test_merge_users.py
subscription/models.py

Attribue par défaut le groupe "Public" aux utilisateurs nouvellement créés, et le groupe "Anciens Cotisants" lorsque les utilisateurs cotisent pour la première fois.

Give default groups to users

---

club/views.py
core/auth/api_permissions.py
core/management/commands/populate.py
core/views/__init__.py
core/views/user.py
pedagogy/api.py
pedagogy/models.py
pedagogy/templates/pedagogy/guide.jinja
pedagogy/templates/pedagogy/uv_detail.jinja
pedagogy/tests/tests.py
pedagogy/views.py

Passage de nos perms maison vers les perms du framework pour la pédagogie.
Ca s'y prête assez bien, puisqu'il n'y a aucune histoire de club : les admins pédagogie voient tout, les autres voient seulement ce qui est modéré et ce qu'ils ont écrit.
Ca va permettre une gestion plus fine des permissions, avec pour objectif :
- les anciens cotisants peuvent voir les UEs et les commentaires modérés.
- les cotisants peuvent ajouter et signaler des commentaires
- les admins pédagogie peuvent tout voir et tout faire, sauf éditer les commentaires des autres utilisateurs
- les auteurs de commentaire peuvent voir leur commentaire, même s'il a été signalé.
Tout ça est indicatif. C'est configurable directement depuis l'interface admin. On peut rajouter ou retirer une permission en deux clics.

Improve pedagogy permissions

---

counter/tests/test_counter.py
counter/views/click.py

Les vendeurs des comptoirs de bureau avaient perdu l'accès à ces comptoirs.
Si un membre du bureau du club était également marqué comme vendeur de ce comptoir, il était également bloqué, quand bien même il était dans le bureau du club.

Fix office counter access

---

counter/models.py
counter/tests/test_customer.py

On ne sélectionnait pas bien les achats (on prenait tout, y compris les achats faits par carte, qui ne peuvent pas être contrebalancés par un rechargement).
Heureusement, cette fonction n'est pas (encore) appelée en prod ailleurs que pour fusionner des utilisateurs, donc il ne devrait pas y avoir eu de conséquences.

fix `CustomerQuerySet.update_balance`

---

core/tests/test_user.py
core/views/forms.py

Le formulaire remplaçait la totalité des groupes de l'utilisateur, c'est-à-dire également les groupes pas affichés dans le formulaire. Ça fait que la soumission du formulaire retirait l'utilisateur de tous ses groupes de groupes et des autres groupes non-gérables manuellement (comme Publique et Anciens Cotisants).
Jusqu'ici, les groupes non-manuels étaient gérés bizarrement, en regardant dynamiquement à chaque fois si l'utilisateur est dans le groupe, donc le bug ne se voyait pas. Maintenant que tous les groupes sont gérés presque de la même manière, ça se voit.

Fix user groups update view

---

core/management/commands/populate.py
core/models.py
core/templates/core/edit.jinja
core/templates/core/user_detail.jinja
core/templates/core/user_tools.jinja
core/views/forms.py
core/views/group.py
docs/tutorial/groups.md
locale/fr/LC_MESSAGES/django.po
sith/settings.py
subscription/tests/test_new_susbcription.py
subscription/tests/test_permissions.py
subscription/urls.py
subscription/views.py

Dans cette PR, je passe la gestion de qui peut créer les perms vers la système de Django, plutôt que notre système semi-hardcodé.
Comme on veut quand même pouvoir changer qui a le droit de créer des cotisations, j'ai aussi rajouté une page sur laquelle on peut gérer les groupes qui ont cette perm. Pour faire ça, j'ai aussi fait quelques ajouts qui pourront peut-être être utiles par la suite :
- Le titre affiché sur la page d'édition telle que générée par `core/edit.jinja` peut-être changé si on lui donne un titre alternatif dans le contexte. C'est pratique dans les cas où la méthode `__str__()` renvoie une chaine de caractère qui rend bizarre pour l'utilisateur final.
- Le template `core/edit.jinja` affiche le message de succès s'il y en a un (en utilisant pour ça l'infrastructure des …

Subscription perms

---

com/api.py
com/models.py
com/static/bundled/com/components/moderation-alert-index.ts
com/static/com/css/news-list.scss
com/templates/com/macros.jinja
com/templates/com/news_detail.jinja
com/templates/com/news_list.jinja
com/tests/test_api.py
com/views.py
core/static/core/style.scss
core/templates/core/macros.jinja
locale/fr/LC_MESSAGES/django.po

Pour commencer, on résoud des problèmes de N+1 queries sur l'affichage des nouvelles sur la page d'accueil.
On change également le choix des nouvelles affichées :
- Les admins voient toutes les nouvelles sur la page d'accueil, y compris les non-modérées
- Les autres voient toutes les nouvelles modérées+celles qu'ils ont écrites (même non-modérées)
On différencie les nouvelles modérées des nouvelles modérées avec un encart qui dit que la nouvelle est en attente de modération :
Si l'utilisateur connecté à la permission de modérer les nouvelles, l'alerte contient également un bouton pour modérer et un bouton pour supprimer. Le flux de modération/suppression des nouvelles : 
[Kooha-2025-01-20-17-38-01.webm](https://github.com/user-attachments/assets/cf4adf76-6992-4308-8e17-f0a3301779c7)
Après …

News list improvements

---

counter/static/bundled/counter/counter-click-index.ts
counter/templates/counter/counter_click.jinja
counter/tests/test_counter.py
counter/views/click.py

Quand un utilisateur se retrouve, par bug ou par malice dans une version antérieure, à un nombre de consignes trop négatives, il ne peut plus consommer du tout au bar tant qu'il n'a pas consigné en plus.
On veut que l'utilisateur ne soit bloqué que pour la déconsigne, pas pour la consigne ni les achats.
C'est réglé ici

Allow transactions on counter when an user has recorded too many products

---

subscription/forms.py
subscription/tests/test_new_susbcription.py

Quand une cotisation est créée pour un nouvel utilisateur, on donne le statut "étudiant" au nouvel utilisateur, s'il s'agit d'une cotisation cursus ou d'une cotisation un semestre ou deux semestres.

Give the student role when creating a new user subscription

---

club/schemas.py
com/api.py
com/schemas.py
com/static/bundled/com/components/moderation-alert-index.ts
com/static/bundled/com/components/upcoming-news-loader-index.ts
com/static/com/css/news-list.scss
com/templates/com/macros.jinja
com/templates/com/news_list.jinja
com/tests/test_api.py
com/views.py
core/management/commands/populate.py
locale/fr/LC_MESSAGES/django.po
locale/fr/LC_MESSAGES/djangojs.po
sith/settings.py

Sur la page d'accueil, on ne limite plus le nombre de nouvelles affichées, mais on affiche les prochains jours où il se passe quelque chose (même s'ils arrivent dans longtemps).
Quand le section prend trop de place, on la rend scrollable.
Et quand on arrive en bas et qu'il y a plus à charger, on met un bouton "voir plus" qui permet de charger les jours d'après.

Allow displaying more news

---

counter/models.py

Répare l'affichage avec trop de chiffres après la virgule quand on annule une vente : 
Après réparation, ça donne ça :

Fix sales display

---

accounting/tests.py
accounting/views.py
com/schemas.py
core/auth/mixins.py
core/management/commands/populate.py
core/static/bundled/utils/api.ts
core/static/core/header.scss
core/templates/core/base.jinja
core/templates/core/base/header.jinja
core/templates/core/page.jinja
core/tests/test_core.py
core/tests/test_user.py
core/views/files.py
core/views/page.py
pyproject.toml
subscription/forms.py
subscription/models.py
uv.lock

- Passage de la vue de logout en POST (cf. https://docs.djangoproject.com/en/4.2/releases/4.1/#log-out-via-get)
- On ne passe plus d'objets non-sauvés en argument de la méthode filter des QuerySet (cf. https://docs.djangoproject.com/en/4.2/releases/4.1/#id2, au 8ème point)
- Changement du chemin d'import de `RouteContext` depuis ninja_extra (cf. https://github.com/eadwinCode/django-ninja-extra/pull/243 et https://github.com/eadwinCode/django-ninja-extra/releases/tag/0.22.4)
- Augmentation de la taille max de pagination de 199 à 200 (cf. https://github.com/eadwinCode/django-ninja-extra/pull/239). Ce changement dans ninja_extra devrait aussi résoudre [cette issue Sentry](https://sentry.ae.utbm.fr/organizations/sentry/issues/176/?environment=production&project=2&query=is%3Aunresolved&referrer …

Fix some deprecations

---

core/models.py
counter/static/bundled/counter/counter-click-index.ts
sas/models.py
sas/static/bundled/sas/viewer-index.ts
sas/templates/sas/picture.jinja
sas/tests/test_model.py

Actuellement, quand quelqu'un crée une photo ou un album dans un album dans lequel il a les droits pour ça sans être admin SAS, la création se fait bien, mais ce qui est crée est non-modéré par défaut et donc invisible.
Celui qui upload une photo ou un album doit donc être en mesure de les voir.

Make SAS pictures visible for their owner

---

.github/workflows/ci.yml
core/views/user.py
galaxy/tests.py
sith/settings.py
sith/urls.py

La galaxy est basiquement une bombe posée sur le site.
Quand la galaxy est générée et qu'on tente d'y accéder, toutes les ressources du PC se retrouvent syphonnées par la Galaxy. 
Mon PC fait pas tourner Cyberpunk 2077, mais c'est pas non plus une patate ; eh bah il freeze. Je ne peux même pas fermer le navigateur ou tuer le processus, parce que le PC ne répond plus du tout. 100% du processeur et la quasi-intégralité de ma RAM y passent.
Jusqu'ici, la Galaxy était accessible, mais sans être référencée, parce qu'elle n'est pas finie. Vu comme la page est dangereuse, je préfère retirer complètement l'URL, en attendant le jour éventuel où ça sera réparé.

Remove galaxy from production

---

.pre-commit-config.yaml
eboutic/api.py
eboutic/static/bundled/eboutic/makecommand-index.ts
eboutic/static/eboutic/css/eboutic.css
eboutic/templates/eboutic/eboutic_makecommand.jinja
eboutic/views.py
locale/fr/LC_MESSAGES/django.po
locale/fr/LC_MESSAGES/djangojs.po

C'était vieux, c'était legacy, et ça a cassé quand on a rajouté la vérification csrf sur l'API.
J'ai juste typescriptifié et arrangé quelques trucs, mais globalement l'idée reste la même qu'avant. A l'occasion, ça pourra être cool d'utiliser plutôt htmx pour le formulaire des infos de facturation.

refactor eboutic command page

---

com/static/com/css/news-list.scss
core/static/core/markdown.scss

On a un petit soucis sur mobile avec les news quand il y a des liens dedans.
J'ai fixé ce problème
Avant :
Après :

Fix news x overflow on mobile

---

com/ics_calendar.py
com/static/bundled/com/components/ics-calendar-index.ts
com/static/com/components/ics-calendar.scss
core/static/core/style.scss
locale/fr/LC_MESSAGES/djangojs.po
sith/settings.py

Ajoute un bouton pour obtenir le lien du calendrier à des fins de synchronisation.
L'ics génère également maintenant des liens absolus pour tous les événements
https://github.com/user-attachments/assets/f6c2531f-7416-4c6e-abf7-a225b8202f04

Remote calendar link for external sync

---

core/management/commands/populate.py
core/schemas.py
core/utils.py
galaxy/management/commands/generate_galaxy_test_data.py
locale/fr/LC_MESSAGES/django.po
sas/api.py
sas/forms.py
sas/models.py
sas/static/bundled/sas/album-index.ts
sas/templates/sas/album.jinja
sas/templates/sas/fragments/album_create_form.jinja
sas/templates/sas/main.jinja
sas/tests/test_api.py
sas/urls.py
sas/views.py

Petit coup de polish sur l'upload de photos.
On passe d'une combinaison jquery/une grosse vue qui fait tout vers une vue plus simple qui ne s'occupe que du rendu de la page avec les actions concrètes qui se font avec d'autres composants.
- la création d'un nouvel album se fait avec un fragment
- l'upload de photos se fait avec un Alpine data qui interagit avec un endpoint d'API
- le formulaire d'upload et le formulaire de création d'album ont été séparés en deux formulaires différents.

Improve SAS upload

---

sas/templates/sas/main.jinja
sas/tests/test_views.py
sas/views.py

Quand un utilisateur anonyme tente d'accéder au site, il reçoit une erreur 500 au lieu du message qui lui dit qu'il doit se connecter.

fix 500 on SAS main page for anonymous users

---

com/static/bundled/com/components/ics-calendar-index.ts

J'ai mieux lu la doc et stackoverflow et j'ai trouvé comment mieux combattre le cache pour les événements

Remove cache workaround on news calendar moderation

---

.env.example
.github/workflows/ci.yml
Procfile.service
docs/explanation/technos.md
docs/tutorial/install-advanced.md
docs/tutorial/install.md
manage.py
pyproject.toml
sith/__init__.py
sith/celery.py
sith/settings.py
uv.lock

Implémentation de la configuration requise pour faire fonctionner celery.
A faire côté serveur : écrire la config pour daemoniser celery.

Use celery for task queue

---

com/static/bundled/com/components/ics-calendar-index.ts
com/static/com/components/ics-calendar.scss
com/templates/com/news_list.jinja
locale/fr/LC_MESSAGES/djangojs.po

ajout d'un bouton permettant de rediriger l'utilisateur vers une page de wiki expliquant comment rajouter le calendrier AE à Google Agenda.

Calendar link help button

---

com/static/bundled/com/components/ics-calendar-index.ts
com/static/com/components/ics-calendar.scss
core/static/bundled/core/tooltips-index.ts
core/static/core/style.scss
core/static/core/tooltips.scss
core/templates/core/base.jinja
package-lock.json
package.json

Les tooltips qu'on avait elles étaient sympa mais elles clippent quand on sort de la zone de vue d'un élément.
Ici, je fait une petite lib js qui permet de faire des tooltips mais qui flottent au dessus de tout pour éviter ça.
L'api est la même mais avec plus d'options de positionnement.

Create a js tooltip library

---

club/forms.py
club/tests/test_sales.py

Quand un club veut regarder les ventes, il n'a pas besoin de voir tous les 109 comptoirs existants (à l'heure où je fais cette PR).
A la place, on filtre pour afficher uniquement les comptoirs :
- Sur lesquels il y a eu des ventes de produits du club (donc ça marche même si le club lié au produit est modifié a posteriori)
- Ou bien sur lesquels il y a un produit du club (donc ça marche même si le produit existe, mais qu'il n'y a encore eu aucune vente)
- Ou bien qui appartiennent explicitement au club

Filter counters in ClubSellingView

---

com/static/bundled/com/components/upcoming-news-loader-index.ts
com/templates/com/news_list.jinja

Répare l'affichage de l'horodatage sur les nouvelles chargées en appuyant sur le bouton "voir plus", sur la page d'accueil.
Avant : 
Après :

fix: datetime format in main page news list

---

core/static/bundled/user/family-graph-index.ts
core/static/user/user_godfathers.scss
core/templates/core/user_godfathers_tree.jinja
package-lock.json
package.json
uv.lock

Un ami dont je tairais le nom ici est très mécontent de ne pas pouvoir voir sa famille entière sur l'arbre des familles.
Il m'a dit, je cite
> j'arrive pas a avoir ma famille au complet
> imagine tu rentee chez toi et tu ne retrouve que la moitié de ton chat
> c'est horrible
Au vu de ces propos qui, je suis certain, dépassaient sa pensée, j'ai ajouté des boutons de contrôle du zoom.
Changements:
* Activer/désactiver le zoom
* Le zoom est désactivé sur mobile par défaut
* Zoomer/dézoomer avec des boutons
* Le tout a été convertit en typescript
*

Add zoom controls to family graph

---

core/management/commands/install_xapian.sh
pyproject.toml

On mettait mal en place les flags de compilation, ce qui fait qu'on compilait sans optimiser le binaire.
Avant :
```python
>>> %timeit list(
SearchQuerySet().models(User).autocomplete(auto=slugify("Géra")).values("id")
)
1.84 ms ± 8.55 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
```
Après :
```python
>>> %timeit list(
SearchQuerySet().models(User).autocomplete(auto=slugify("Géra")).values("id")
)
507 µs ± 4.93 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
```
Résultat : perfs x3.63 (sur un jeu de 900 utilisateurs)
Avant :
```python
>>> %timeit list(
SearchQuerySet().models(ForumMessage).autocomplete(auto=slugify("Appel")).values("id")
)
170 ms ± 1.97 per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
Après :
```python
>>> %timeit list( …
```

fix: xapian compilation flags

---

subscription/models.py
subscription/tests/test_new_subscription.py
subscription/views.py

Si un utilisateur faisait sa première cotisation alors qu'il avait déjà un compte AE (par exemple, en effectuant un achat sur l'eboutic avant sa cotisation), alors il pouvait se retrouver hors du groupe Anciens cotisants.
J'ai aussi bougé le code qui gère l'envoi du mail à la première cotisation. Avant, on l'envoyait à chaque première cotisation, ce qui veut dire qu'un utilisateur qui avait déjà un compte utilisateur et qui faisait sa première cotisation recevait le mail, alors qu'on voudrait l'envoyer uniquement à ceux dont le compte est créé automatiquement avec la cotisation, afin de leur dire comment y accéder. Maintenant, c'est le fragment de création des cotisations pour des nouveaux utilisateurs qui gère l'envoi du mail.

fix old subscribers group attribution

---

core/api.py
core/management/commands/populate_more.py
core/schemas.py
locale/fr/LC_MESSAGES/django.po
subscription/forms.py
subscription/static/bundled/subscription/creation-form-existing-user-index.ts
subscription/static/subscription/css/subscription.scss
subscription/tests/test_new_subscription.py

Oblige à renseigner la date de naissance lors de la création d'une cotisation pour un utilisateur existant si ce dernier ne l'a pas déjà donnée.
Exemple :
Pour ne pas surcharger le formulaire, l'input pour la date de naissance est caché quand aucun utilisateur n'est sélectionné ou que l'utilisateur sélectionné a déjà une date de naissance renseignée.

Subscription birthday

---

core/models.py
core/tests/test_page.py
core/views/page.py

Le mécanisme de vérification des droits essayait de récupérer `PageRev.owner_group_id`, qui n'existe pas. J'ai réparé ça sommairement en rajoutant la méthode `PageRev.is_owned_by`, mais c'est vraiment juste un bout de scotch placé là. Pour vraiment réparer ça, il faudrait tout réécrire.

fix: 500 on page properties edit

---

core/templates/core/base.jinja

Ça fait planter les formulaires, c'est chiant, ça dégage

Remove `s` shortcut for search bar
